###
GET http://localhost:3000/test

###
GET http://localhost:3000/api/tasks

###
GET http://localhost:3000/api/tasks/1

###
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
  "task": "test"
}

###
PATCH http://localhost:3000/api/tasks/1
Content-Type: application/json

{
  "task": "Newest task name"
}


###
DELETE http://localhost:3000/api/tasks/1